version: '3'

volumes:
  db:
  nextcloud:
  apps:
  config:
  data:

services:
  db:
    image: postgres
    container_name: nextcloud_db
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - env

  redis:
    image: redis
    container_name: redis
    restart: always

  app:
    image: nextcloud:apache
    container_name: nextcloud_app
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
      - apps:/var/www/html/custom_apps
      - config:/var/www/html/config
      - data:/var/www/html/data
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - env
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:apache
    container_name: nextcloud_cron
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
