version: '3'

volumes:
  db:
  nextcloud:
  apps:
  config:
  data:

services:
  db:
    image: postgres
    restart: always
    container_name: nextcloud_db
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}

  redis:
    image: redis
    container_name: redis
    restart: always

  app:
    image: nextcloud
    container_name: nextcloud_app
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
      - apps:/var/www/html/custom_apps
      - config:/var/www/html/config
      - data:/var/www/html/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
